# -*- coding: utf-8 -*-
"""run_parameters_CRED_chats_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kxuc0O87BEPygPH9usxa6EP-LsWG1bVF
"""

#@title DEFINING FUNCTIONS, IMPORTING LIBRARIES

!pip install -q -U google-generativeai

import pandas as pd
import re
import spacy
import google.generativeai as genai
import json
import time
import textwrap
import os


def remove_short_calls(df, primary_info):
    primary_info.rename(columns={'Request_id': 'request_id'}, inplace=True)
    merge_df = pd.merge(df, primary_info[['request_id' , 'Time_duration_of_Call']], on='request_id')
    filtered_df = merge_df[merge_df['Time_duration_of_Call'] >= 120]
    filtered_df = filtered_df.drop(columns=['request_id'])
    return filtered_df

def extract_json_objects(response_text):
    json_objects = []
    json_str = re.search(r'```json\s*({.*?})\s*```', response_text, re.DOTALL)
    if json_str:
        json_obj = json.loads(json_str.group(1))
        json_objects.append(json_obj)
    return json_objects

#@title INITALIZATION - LLM
# genai.configure(api_key=os.getenv('AIzaSyCRL1S79rvEGbhw8nN-M7_VUEAwISdqcXE'))
genai.configure(api_key='AIzaSyDvocQSQFzwruJS12Jx1xgRxa3CVzBrBLo')
model = genai.GenerativeModel('gemini-1.5-flash')

#@title LOADING CRED CONVERSATIONS

from google.colab import drive
drive.mount('/content/drive')

cred_conversational_data_path_ = '/content/drive/MyDrive/Vocab_AI_Operations/CRED/Cred/Data'
the_file_name = 'TAReport (30).xlsx'
the_sheet_name = 'Transcript'

df = pd.read_excel(f'{cred_conversational_data_path_}/{the_file_name}', sheet_name=the_sheet_name)
primary_info = pd.read_excel(f"{cred_conversational_data_path_}/{the_file_name}" , sheet_name='Primary Info')

# df = remove_short_calls(df, primary_info)

print(df.columns)

#@title PROMPTS FOR QUALITY PARAMETERS

##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
llm_instructions_ = """
    You are a helpful and objective AI assistant. Please read the above transcript.
    Follow the instructions below to check if the agent has followed the provided guidelines during the conversation.
    Your output should be deterministic and consistent for the same prompt.
    Mark the output as 'Met' if the agent’s greeting matches the guidelines provided. Otherwise, mark it as 'Not Met'.
    Provide a reason for your decision.
    If you mark it as 'Met' give the exact statement used by the agent in the conversation.
    If you mark it as 'Not Met' explain what was missing or incorrect based on the guidelines.
"""
##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
assessment_guidelines_ = """
    - The agent can switch between English and Hindi or use a mix of languages.
    - Minor variations in phrasing are acceptable as long as the intent matches the guideline.
    - Evaluate based on intent and not strict wording.
"""

##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
opening_guidelines = """
 - Greet the customer by using any 'Good morning/afternoon/evening/ Hello'
    - The agent must introduce themselves with their name: <name>
    - The agent confirm or ask the customer's name: <customer name>

    Agent can introduce themselves as follwings -
    - this is <name>
    - my name is <name>
    - <name> this side
    - myself is <name>
    - <name> calling from

    the confirmation statements can be any one of the following -
    - Am I speaking with <customer name>
    - Is this <customer name>

    The agent doesn't need to say his/her full name.
    If the agent use these kind of statement anywhere in the trancript mark it as Met.

"""
##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
closing_guidelines = """
  - check if the agent ask the client for further help
  - ask to share the feedback for the conversation
  - ask the customer to transferring the call for the feedback.
  - close the chat with the proper greetings similar to the statement - 'I hope you have a great day ahead'
  - if the customer did not end the call ask him to cut the call politely.
  - if the customer becomes abusive on the call, agent can say similar statment :
    - I understand that you're frustrated, but I need to let you know that I can only continue this conversation if it remains respectful.
  - if the customer continues for abuse -  I am sorry, however, I am forced to disconnect the call. Feel free to reach out again when you're ready to discuss your concerns respectfully.

"""

##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
hold_guidelines = """
    The agent can use the following statements or similar statements while putting a call on hold -
    - "May I place your call on hold for 2 min?"
    - "Thank you for being on hold Sir/ Mam."
    - "May I place this call on hold <> minutes to check the information for you."
    - "To check the information for you may I place this call on hold for <> minutes."
    - "Kya mein aapki call ko <> Hold pe rak saktha / Sakti hoon information check karne ke liye?"
    - "Aapki jaankari check karne ke liye kya mein aapka/aapki call <> minute hold pe rak saktha sakti hoon sir/madam?"
    - "sir/madam ek minute hold kijeye"
"""

##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
assistance_guidelines = """
    The agent can use the following statements or similar statements to find if the customer needs further assistance -
    - Iske alawa koi aur sahayata meri taraf se/ Iske alawa koi aur jankari
    - Is there anything else apart from this I may assist you with
"""
##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##
reassurance_guidelines_="""
    The agent can assured the customer by providing statements similar to the below statements -
    - You can rest assured that we are working on this right now.
    - I will get back to you as soon as possible
    - I assure you, we will handle this matter promptly.
    - We are committed to resolving this for you as quickly as possible.
    - I will personally ensure that this issue is taken care of.
    - We have already started looking into this and will update you shortly.
    - Our support team is here for you, and we will see this through to the end.
    - I have all the necessary information and will make sure this gets fixed.
    - We take this matter seriously and will address it immediately.
    - We are here to help and will make sure this is resolved for you.
    - We appreciate your patience and will resolve this as quickly as possible.
    - I will keep you updated on the progress and next steps.

"""

output_format_guidelines_ = """
  Provide your assessment in a clear and concise manner. Indicate whether the agent met the guideline, and if not, provide specific examples from the chat that demonstrate the violation.
    **Output Format:**
    json
    {{
        'Value': 'Met' or 'Not Met',
        'Evidence': '<detailed evidence>'
    }}
"""
##-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-##


##---------------------------------------------##
prompt_opening = f"""
    **Assessment Instructions**
    {llm_instructions_}
    **Guidelines:**
    {opening_guidelines}
    **Output formatting considerations**
    {output_format_guidelines_}
    **Assessment Criteria:**
    {assessment_guidelines_}

    **Examples:**
    - If the agent said "विजय calling from Cred" and "Am I speaking with गोविंद?", the output should be:
    json
    {{
        "Value": "Yes",
        "Evidence": "The agent introduced themselves as 'विजय calling from Cred' and confirmed the customer's name with 'Am I speaking with गोविंद?'"
    }}
    - If the agent said "Hello, this is from Cred" without a name, and "Is this गोविंद?", the output should be:
    json
    {{
        "Value": "No",
        "Evidence": "The agent did not provide their name and only confirmed the customer’s name with 'Is this गोविंद?'."
    }}
    **Notice 1:** The agent may combine Hindi and English guidelines in a sentence, and this is acceptable.
    **Notice 2:** The agent's and customer's names can be in Hindi or English, and either is correct.
"""



prompt_closing = f"""
    **Assessment Instructions**
    {llm_instructions_}
    **Guidelines:**
    {closing_guidelines}
    **Output formatting considerations**
    {output_format_guidelines_}
    **Assessment Criteria:**
    {assessment_guidelines_}
    - All the cases where the agent had no opportunity to close the call, that is customer cut the call before agent's statement Mark it as "MET" instead of "NOT MET"
    - If the customer is ending the call abruptly, mark is as 'MET'.
    - If the customer cut the call before the agent had a chance to ask for feedback or closing statement, mark it as 'MET'.
    - It is mandatory for the agent to ask the customer for transferring the call for feedback. If he is suggesting the customer for feedback or directly transferring for feedback then mark the closing parameter as "Not Met"

    **Examples:**
    - If the agent said “Is there anything else I can help you with?” and “Great! Before we end this call, may I request you to share your valuable feedback basis our conversation?,” the output should be:
    ```json
    {{
        'Value': 'Met'
        'Evidence': 'The agent asked if there was anything else they could help with and requested feedback before ending the call.'
    }}
    ```
    - If the agent did not ask for feedback but did ask if there was anything else to help with, the output should be:
    ```json
    {{
        'Value': 'Not Met',
        'Evidence': 'The agent asked if there was anything else to help with but did not request feedback before ending the call.'
    }}
    ```
    **Notice 1:** The agent may combine Hindi and English in a sentence, which is acceptable.
    **Notice 2:** Ensure leniency in evaluating the phrasing as long as the guideline’s intent is met.
"""


prompt_reassurance = f"""
    **Assessment Instructions**
    {llm_instructions_}
    **Guidelines:**
    {closing_guidelines}
    **Output formatting considerations**
    {output_format_guidelines_}
    **Assessment Criteria:**
    {assessment_guidelines_}
    - An agent should be able to create a sense and atmosphere where the customer feels assured.
    **Output Format:**
    ```json
    {{
        'Value': 'Met' or 'Not Met',
        'Evidence': <detailed evidence>
    }}
    ```
    **Notice 1:** The agent may combine Hindi and English in a sentence, which is acceptable.
    **Notice 2:** Ensure leniency in evaluating the phrasing as long as the guideline’s intent is met.
"""


prompt_hold_ = f"""

    **Assessment Instructions**
    {llm_instructions_}
    You need to identify if the agent has used any of these or similar statements anywhere in the conversation for putting a customer on hold
    **Guidelines:**
    {hold_guidelines}
    **Output formatting considerations**
    {output_format_guidelines_}
    **Assessment Criteria:**
    {assessment_guidelines_}

    **Notice 1:** The agent may combine Hindi and English in a sentence, which is acceptable.
    **Notice 2:** Ensure leniency in evaluating the phrasing as long as the guideline’s intent is met.
"""


prompt_further_assistance_ = f"""

    **Assessment Instructions**
    {llm_instructions_}
    You need to identify if the agent has used any of these or similar statements anywhere in the conversation for putting a customer on hold
    **Guidelines:**
    {assistance_guidelines}
    **Output formatting considerations**
    {output_format_guidelines_}
    **Assessment Criteria:**
    {assessment_guidelines_}

    **Notice 1:** The agent may combine Hindi and English in a sentence, which is acceptable.
    **Notice 2:** Ensure leniency in evaluating the phrasing as long as the guideline’s intent is met.
"""

#@title PROCESS CONVERSATIONS AND GENERATE OUTPUTS

the_safety_settings_ = {
    'HATE': 'BLOCK_NONE',
    'HARASSMENT': 'BLOCK_NONE',
    'SEXUAL' : 'BLOCK_NONE',
    'DANGEROUS' : 'BLOCK_NONE'
}


def process_conversation_with_prompt_(the_df, the_prompt_):
  results = []
  failed_chats = []
  for index, row in df.iterrows():
    this_conversation_ = row["transcript"]
    this_request_id = row["request_id"]
    the_full_prompt_ = this_conversation_ + the_prompt_
    try:
        response = model.generate_content(the_full_prompt_, safety_settings=the_safety_settings_)
        extracted_info = extract_json_objects(response.text)
    except Exception as e:
      failed_chats.append((index, this_request_id ,this_conversation_))
      print(f"Failed chat: {this_request_id} due to error: {e}")
      continue
    print(extracted_info)
    result = [item['Value'] for item in extracted_info]
    evidence = [item['Evidence'] for item in extracted_info]
    results.append({
        'request_id': this_request_id,
        'parameter_result': result,
        'parameter_evidence': evidence
    })
    time.sleep(5)
  return results, failed_chats


def process_failed_chats_(the_failed_chats, the_prompt_):
  retry_results = []
  for row in the_failed_chats:
      index = row[0]
      this_request_id = row[1]
      this_conversation_ = row[2]
      the_full_prompt_ = this_conversation_ + the_prompt_
      try:
        response = model.generate_content(this_conversation_, safety_settings=the_safety_settings_)
        extracted_info = extract_json_objects(response.text)
      except Exception as e:
        print(f"Failed chat: {this_request_id} due to error: {e}")
        continue
      print(extracted_info)
      result = [item['Value'] for item in extracted_info]
      evidence = [item['Evidence'] for item in extracted_info]
      retry_results.append({
          'request_id': this_request_id,
          'parameter_result': result,
          'parameter_evidence': evidence
      })
      time.sleep(5)
  return retry_results


def merge_results_and_retries_(the_results_, the_retry_results):
  res_df = pd.DataFrame(the_results_)
  if the_retry_results:
      retry_df1 = pd.DataFrame(the_retry_results)
      res_df = pd.concat([res_df, retry_df1], ignore_index=True)
  return res_df


##--__--__--__--__--__--__--__--__--__--__--__--__--__--__##
 # FOR CHAT OPENING
opening_results, opening_failed_chats = process_conversation_with_prompt_(df, prompt_opening)
opening_retry_results = process_failed_chats_(opening_failed_chats, prompt_opening)
opening_res_df = merge_results_and_retries_(opening_results, opening_retry_results)
##--__--__--__--__--__--__--__--__--__--__--__--__--__--__##
 # FOR CHAT CLOSING
closing_results, closing_failed_chats = process_conversation_with_prompt_(df, prompt_closing)
closing_retry_results = process_failed_chats_(closing_failed_chats, prompt_closing)
closing_res_df = merge_results_and_retries_(closing_results, closing_retry_results)
##--__--__--__--__--__--__--__--__--__--__--__--__--__--__##
 # FOR REASSURANCE
reassurance_results, reassurance_failed_chats = process_conversation_with_prompt_(df, prompt_reassurance)
reassurance_retry_results = process_failed_chats_(reassurance_failed_chats, prompt_reassurance)
reassurance_res_df = merge_results_and_retries_(reassurance_results, reassurance_retry_results)
##--__--__--__--__--__--__--__--__--__--__--__--__--__--__##
 # FOR HOLD
hold_results, hold_failed_chats = process_conversation_with_prompt_(df, prompt_hold_)
hold_retry_results = process_failed_chats_(hold_failed_chats, prompt_hold_)
hold_res_df = merge_results_and_retries_(hold_results, hold_retry_results)
##--__--__--__--__--__--__--__--__--__--__--__--__--__--__##
 # FOR FURTHER ASSISTANCE
furtherasst_results, furtherasst_failed_chats = process_conversation_with_prompt_(df, prompt_further_assistance_)
furtherasst_retry_results = process_failed_chats_(furtherasst_failed_chats, prompt_further_assistance_)
furtherasst_res_df = merge_results_and_retries_(furtherasst_results, furtherasst_retry_results)
##--__--__--__--__--__--__--__--__--__--__--__--__--__--__##